# Generated by Django 5.1.3 on 2024-11-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='current_city',
            field=models.CharField(blank=True, default='default_city', max_length=50),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='grad_year',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
