# Generated by Django 5.1.3 on 2024-11-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_alter_alumniinfo_current_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumniinfo',
            name='current_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumniinfo',
            name='grad_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
